package main

import (
	"context"
	"log"
	"net/http"

	storev1 "github.com/coopnorge/bendik-connectrpc/coopnorge/store/v1"                       // generated by protoc-gen-go
	storev1connect "github.com/coopnorge/bendik-connectrpc/coopnorge/store/v1/storev1connect" // generated by protoc-gen-connect-go

	"connectrpc.com/connect"
)

func main() {
	client := storev1connect.NewStoreInformationAPIClient(
		http.DefaultClient, // Normal HTTP Client
		"http://localhost:8080",
		// connect.WithGRPC(),
	)
	res, err := client.GetStore(
		context.Background(),
		connect.NewRequest(&storev1.GetStoreRequest{Id: "1"}),
	)
	if err != nil {
		log.Println(err)
		return
	}
	log.Printf("Got store with ID %s and Name %s", res.Msg.Store.GetId(), res.Msg.Store.GetName())
}
