linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - gofmt
  - revive
  - gosimple
  - govet
  - ineffassign
  - misspell
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
issues:
  exclude-use-default: false
  exclude-rules:
  - path: _test[.]go
    linters:
      - errcheck
