FROM golang:1.20-buster@sha256:eb3f9ac805435c1b2c965d63ce460988e1000058e1f67881324746362baf9572

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt update \
    && apt-get install -y protobuf-compiler

COPY Makefile *.sha256sum go.mod go.sum tools.go /tmp/bootstrap/

RUN cd /tmp/bootstrap/ \
    && make tools_dir=/usr/local/bin toolchain GOFLAGS=
