FROM golang:1.16-buster@sha256:0dd361b197272f3a26462030e4a387ac9a06495aa63ac5e9a8b0b72df8cfdba1

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt update \
    && apt-get install -y protobuf-compiler

COPY Makefile *.sha256sum go.mod go.sum tools.go /tmp/bootstrap/

RUN cd /tmp/bootstrap/ \
    && make tools_dir=/usr/local/bin toolchain GOFLAGS=
