FROM golang:1.16-buster@sha256:19bc888c9bc1cd6279263449bb3b8c780190aa14706c93ac44d44c3e01f199c2

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt update \
    && apt-get install -y protobuf-compiler

COPY Makefile *.sha256sum go.mod go.sum tools.go /tmp/bootstrap/

RUN cd /tmp/bootstrap/ \
    && make tools_dir=/usr/local/bin toolchain GOFLAGS=
