version: "3"

services:
  devtools:
    build:
      context: devtools
      dockerfile: Dockerfile
    privileged: true
    environment:
      GOMODCACHE: /root/.cache/go-mod
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    working_dir: /srv/workspace
    volumes:
      - .:/srv/workspace:z
      - ${_XDG_CACHE_DIR:-xdg-cache-home}:/root/.cache
      - ${DOCKER_CONFIG:-~/.docker}:/root/.docker
      - ${LOCALSTATEDIR:-devtools-var}:/srv/workspace/var
    # command: "modd --debug --notify --file modd.conf"
    ports:
      - "127.0.0.1:32604:32604"
  grpcurl:
    image: docker.io/fullstorydev/grpcurl:latest@sha256:085e183ca334eb4e81ca81ee12cbb2b2737505d1d77f5e33dabc5d066593d998
    network_mode: host
  mockoauth2:
    image: ghcr.io/navikt/mock-oauth2-server:3.0.1@sha256:19dbd608fc3587beedd0cbd9597f0e8f54e7c394ee3faf17aa13946e9c68338d
    restart: always
    environment:
      JSON_CONFIG_PATH: /tmp/config/mock-oauth2-server.json
    ports:
      - "127.0.0.1:31309:8080/tcp"
    volumes:
      - ./test/conf/mockoauth2/:/tmp/config/:ro,z
volumes:
    xdg-cache-home: {}
    devtools-var: {}
